apiVersion: v1
kind: Service
metadata:
  name: microservice-webapi-service
  labels:
    name: microservice-webapi-service
    app: microservice
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: microservice-webapi
    type: microservice