name: GitHub Actions DotNet
on: 
  push:
    paths-ignore:
      - '**/*.md'
      
jobs:
  Job-DotNet-Push:
    runs-on: ubuntu-latest
    env:
      DOTNET_CORE_VERSION: 5.0.x
      DOTNET_CLI_TELEMETRY_OUTOUT: 1
      DOTNET_NO_LOGO: true
      BUILD_CONFIGURATION: Release
      PROJECT_PATH: '01-Servicio/Services.WebApi'
      PROJECT_TEST_PATH: '02-Aplicacion-Test/Application.Test'
    steps:
      - name: Check out repository code ('${{ github.repository }}' cloned to runner)
        uses: actions/checkout@v2
        
      - name: Setup .NET Core SDK (${{ env.DOTNET_CORE_VERSION }})
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
          
      - name: Restore Packages
        run: dotnet restore "${{ env.PROJECT_PATH }}"
        
      - name: Build - .NET Core ${{ env.DOTNET_CORE_VERSION }}
        run: dotnet build --configuration ${{ env.BUILD_CONFIGURATION }}
        working-directory: "${{ env.PROJECT_PATH }}"
        
      - name: Unit Tests
        run: dotnet test ${{ env.PROJECT_TEST_PATH }}
